# Generated by Django 4.0.2 on 2022-05-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, unique=True)),
                ('last_name', models.CharField(max_length=120)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('address1', models.CharField(max_length=120)),
                ('address2', models.CharField(max_length=120)),
            ],
        ),
    ]
