# Generated by Django 4.0.2 on 2022-05-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
